### PR TITLE
Merge contributions -> master.

### PR DESCRIPTION
**Pull request by rohitjethoe**
Added more attributes to HTML multiple HTML tags such as <a>,  and <link>. Also added some SEO meta tags.

### CODE REVIEW

**Comment by rohitjethoe** [comment]
I don't think landing was rendered. I can render it if you want it but on what route would you like to render the landing.ejs?

**Comment by rohitjethoe** [comment]
I've fixed the content of the copyright and the description.

**Comment by agrim19** [comment]
> I don't think landing was rendered. I can render it if you want it but on what route would you like to render the landing.ejs?

No do not do that. The links have been setup with specific requirements. @aastha985 We can delete the page.

**Comment by agrim19** [comment]
> 3. Change copyright in meta tag to "Asha Akanksha Foundation"
>    Other changes look good to me. @agrim19 maybe we can test this before merging or put some checks?
I will do that

**Comment by agrim19** [comment]
@rohitjethoe It seems like you have upgraded to ES6 in just a single file. That breaks the consistency a little. Either you could make another commit after changing it everywhere or I could add an issue for that and a separate PR could be added later(in this case you will need to revert the changes in this file too). What would you prefer?

**Comment by agrim19** [comment]
Also, multiple issues have been addressed in this single PR. Could you reply to this comment and list the issues you have fixed so they can be closed once this is merged.

> @rohitjethoe It seems like you have upgraded to ES6 in just a single file. That breaks the consistency a little. Either you could make another commit after changing it everywhere or I could add an issue for that and a separate PR could be added later(in this case you will need to revert the changes in this file too). What would you prefer?

**Comment by rohitjethoe** [comment]
> @rohitjethoe It seems like you have upgraded to ES6 in just a single file. That breaks the consistency a little. Either you could make another commit after changing it everywhere or I could add an issue for that and a separate PR could be added later(in this case you will need to revert the changes in this file too). What would you prefer?

I can do it in other files too. Give me like an hour.

**Comment by rohitjethoe** [comment]
> Also, multiple issues have been addressed in this single PR. Could you reply to this comment and list the issues you have fixed so they can be closed once this is merged.

@agrim19 I have fixed the following issues

> Upgrade to ES6
> Add Add SEO meta tags 
> Add alt to img tags 
> Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. 
> put this `<meta name="theme-color" content="#a43692" />` in head tag

**Comment by rohitjethoe** [comment]
I think everything is done now.

**Comment by agrim19** [comment]
> I think everything is done now.

Great job Rohit. We're merging now.

**Pull request merged**
