### PR TITLE
# Changed README and added LICENSE.

### PR DESCRIPTION
**Pull request by rohitjethoe**

### CODE REVIEW

**Comment by aastha985** [comment]
@agrim19 Please review this PR. The run instruction and name are not correct according to me.

**Comment by agrim19** [comment]
> 
The name should be 'Aastha' only. Just make this one change and I will merge the PR

**Comment by rohitjethoe** [comment]
@agrim19  Done.

**Comment by aastha985** [comment]
@rohitjethoe Please add the technologies used part which you removed back.

**Comment by rohitjethoe** [comment]
@aastha985 @agrim19 Done.

**Pull request merged**
